use std::collections::HashMap;

use anyhow::{bail, Result};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ---- Everything below lives INSIDE the encrypted payload ----
// The relay never sees these deserialized.

/// Decrypted message content. Visible to sender and recipients only.
/// Serialized to bytes, then (eventually) MLS-encrypted into the opaque
/// payload field of relay messages.
#[serde_with::serde_as]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClearMessage {
    Chat {
        text: String,
    },
    Payment {
        /// Session ID generated by the payer at Request time.
        /// Travels in every PaymentAction message so both sides can correlate
        /// actions to the same payment, and so the payee can match a tx to a
        /// session if app state is lost (also written to the shielded memo field).
        session_id: Uuid,
        action: PaymentAction,
    },
    Ack {
        /// ID of the message being acknowledged.
        ref_id: Uuid,
    },
    /// User self-description broadcast. Travels as an opaque encrypted payload —
    /// the relay never deserializes this. Clients store the most-recent profile
    /// for each peer in memory. Field names and values are user-defined; the
    /// only constraint is size (enforced client-side before sending).
    Profile {
        fields: HashMap<String, String>,
    },
    /// Initiates a chunked file transfer. Sent before the first FileChunk.
    /// Receiver uses transfer_id to correlate subsequent FileChunk messages.
    FileHeader {
        transfer_id: Uuid,
        /// Original filename (basename only — no path components).
        name: String,
        /// Total file size in bytes.
        size_bytes: u64,
        /// Lowercase hex-encoded SHA-256 of the complete file bytes.
        sha256_hex: String,
        /// Number of FileChunk messages that follow (0-indexed seq 0..total_chunks).
        total_chunks: u32,
        /// MIME type string (e.g. "image/jpeg", "application/octet-stream").
        mime_type: String,
    },
    /// One chunk of a chunked file transfer.
    /// data is the raw binary slice; serializes as base64 in JSON.
    FileChunk {
        transfer_id: Uuid,
        /// 0-based chunk sequence number.
        seq: u32,
        #[serde_as(as = "serde_with::base64::Base64")]
        data: Vec<u8>,
    },
}

/// The four steps of P2P payment negotiation, plus an error response.
/// All variants travel as encrypted payloads — the relay cannot distinguish
/// payment negotiation from ordinary chat.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "action", rename_all = "snake_case")]
pub enum PaymentAction {
    /// Payer tells payee: "I want to send you X on chain Y."
    Request { chain: Chain, amount_zatoshi: u64 },
    /// Payee provides a fresh receive address.
    Address { chain: Chain, address: String },
    /// Payer confirms broadcast.
    Sent {
        chain: Chain,
        tx_hash: String,
        amount_zatoshi: u64,
    },
    /// Payee confirms receipt detected on chain.
    Confirmed { tx_hash: String },
    /// Sent when a PaymentAction arrives for an unrecognized session_id.
    ///
    /// This handles two cases:
    /// 1. Duplicate message: peer retransmitted an already-completed action.
    /// 2. Lost state: peer reconnected and local session state was not persisted.
    ///
    /// The receiver should treat this as a terminal state for the referenced session.
    Unknown { reason: String },
    /// Either party cancels an in-progress session.
    /// Receiver should discard the session and surface a cancellation message.
    Cancelled { reason: String },
}

/// In-memory payment session state.
///
/// Tracks the lifecycle of a single P2P payment negotiation.
/// The payer creates the session (generating the `id`) at Request time.
/// Persistence to the wallet DB is Phase 2 work (nie-neg).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentSession {
    /// Unique session identifier.  Generated by the payer; travels in all
    /// PaymentAction messages and is written to the shielded memo field.
    pub id: Uuid,
    /// Which chain this payment is on.
    pub chain: Chain,
    /// Payment amount in zatoshi (1 ZEC = 10^8 zatoshi).
    /// Stored as integer to avoid floating-point representation issues.
    pub amount_zatoshi: u64,
    /// The other party's pub_id (hex-encoded SHA-256 of their Ed25519 verifying key).
    pub peer_pub_id: String,
    /// Whether we are paying or receiving.
    pub role: PaymentRole,
    /// Current state of the negotiation.
    pub state: PaymentState,
    /// Unix timestamp (seconds since epoch). Use i64 to avoid SQLite datetime format pitfalls.
    pub created_at: i64,
    /// Unix timestamp (seconds since epoch).
    pub updated_at: i64,
    /// Transaction hash, populated after Sent is broadcast.
    pub tx_hash: Option<String>,
    /// Receive address provided by the payee.
    pub address: Option<String>,
}

/// Whether this peer is paying or receiving in a payment session.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PaymentRole {
    Payer,
    Payee,
}

/// Current phase of a payment session.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PaymentState {
    /// Payer sent Request; waiting for payee's Address.
    Requested,
    /// Payee sent Address; payer should now broadcast.
    AddressProvided,
    /// Payer broadcast the tx and sent Sent; waiting for Confirmed.
    Sent,
    /// Payee confirmed receipt on-chain.  Terminal success state.
    Confirmed,
    /// Session failed or was abandoned.  Terminal failure state.
    Failed,
    /// Session was cancelled by one party or timed out (24 h without advance).
    /// Terminal state; distinct from Failed so UI can show a different message.
    Expired,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Chain {
    Zcash,
    Monero,
    Mobilecoin,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn profile_serializes_with_correct_tag() {
        let mut fields = HashMap::new();
        fields.insert("status".to_string(), "away".to_string());
        fields.insert("favcolor".to_string(), "red".to_string());
        let msg = ClearMessage::Profile { fields };
        let json = serde_json::to_string(&msg).unwrap();
        // Must carry the "type":"profile" tag per ClearMessage serde config.
        assert!(json.contains("\"type\":\"profile\""), "got: {json}");
        assert!(json.contains("\"status\":\"away\""), "got: {json}");
    }

    #[test]
    fn profile_roundtrips() {
        let mut fields = HashMap::new();
        fields.insert("gneder".to_string(), "🏳️‍🌈".to_string());
        fields.insert("blood_type".to_string(), "B+".to_string());
        let original = ClearMessage::Profile { fields };
        let json = serde_json::to_string(&original).unwrap();
        let decoded: ClearMessage = serde_json::from_str(&json).unwrap();
        let ClearMessage::Profile { fields: got } = decoded else {
            panic!("wrong variant after roundtrip");
        };
        assert_eq!(got["gneder"], "🏳️‍🌈");
        assert_eq!(got["blood_type"], "B+");
    }

    #[test]
    fn payment_message_carries_session_id() {
        let session_id = Uuid::new_v4();
        let msg = ClearMessage::Payment {
            session_id,
            action: PaymentAction::Request {
                chain: Chain::Zcash,
                amount_zatoshi: 10_000_000, // 0.1 ZEC * 10^8
            },
        };
        let json = serde_json::to_string(&msg).unwrap();
        // Must carry both session_id and action tag.
        assert!(json.contains("\"type\":\"payment\""), "got: {json}");
        assert!(
            json.contains(&format!("\"session_id\":\"{}\"", session_id)),
            "got: {json}"
        );
        assert!(json.contains("\"action\":\"request\""), "got: {json}");
    }

    #[test]
    fn payment_message_roundtrips() {
        let session_id = Uuid::new_v4();
        let original = ClearMessage::Payment {
            session_id,
            action: PaymentAction::Confirmed {
                tx_hash: "abc123def456".to_string(),
            },
        };
        let json = serde_json::to_string(&original).unwrap();
        let decoded: ClearMessage = serde_json::from_str(&json).unwrap();
        let ClearMessage::Payment {
            session_id: got_id,
            action: PaymentAction::Confirmed { tx_hash },
        } = decoded
        else {
            panic!("wrong variant after roundtrip");
        };
        assert_eq!(got_id, session_id);
        assert_eq!(tx_hash, "abc123def456");
    }

    #[test]
    fn unknown_payment_action_roundtrips() {
        let session_id = Uuid::new_v4();
        let msg = ClearMessage::Payment {
            session_id,
            action: PaymentAction::Unknown {
                reason: "session not found".to_string(),
            },
        };
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"action\":\"unknown\""), "got: {json}");
        let decoded: ClearMessage = serde_json::from_str(&json).unwrap();
        let ClearMessage::Payment {
            action: PaymentAction::Unknown { reason },
            ..
        } = decoded
        else {
            panic!("wrong variant");
        };
        assert_eq!(reason, "session not found");
    }

    #[test]
    fn payment_session_roundtrips() {
        let session = PaymentSession {
            id: Uuid::new_v4(),
            chain: Chain::Zcash,
            amount_zatoshi: 1_000_000,
            peer_pub_id: "a".repeat(64),
            role: PaymentRole::Payer,
            state: PaymentState::Requested,
            created_at: 0,
            updated_at: 0,
            tx_hash: None,
            address: None,
        };
        let json = serde_json::to_string(&session).unwrap();
        let decoded: PaymentSession = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.id, session.id);
        assert_eq!(decoded.amount_zatoshi, 1_000_000);
        assert_eq!(decoded.role, PaymentRole::Payer);
        assert_eq!(decoded.state, PaymentState::Requested);
    }

    #[test]
    fn payment_action_request_wire_format_is_integer() {
        // Oracle: serde_json serializes u64 as a JSON number (no quotes).
        // 0.001 ZEC = 100_000 zatoshi (1 ZEC = 10^8 zatoshi, external fact).
        let action = PaymentAction::Request {
            chain: Chain::Zcash,
            amount_zatoshi: 100_000,
        };
        let json = serde_json::to_string(&action).unwrap();
        // Field must be a JSON integer, not a string
        assert!(
            json.contains("\"amount_zatoshi\":100000"),
            "amount_zatoshi must serialize as integer, got: {json}"
        );
        // Must not contain the old field name
        assert!(
            !json.contains("\"amount\""),
            "old 'amount' field must not be present, got: {json}"
        );
        // Must not be quoted (a string)
        assert!(
            !json.contains("\"amount_zatoshi\":\""),
            "amount_zatoshi must not be a string, got: {json}"
        );
    }

    #[test]
    fn payment_action_sent_wire_format_is_integer() {
        // Oracle: same as above. 0.1 ZEC = 10_000_000 zatoshi.
        let action = PaymentAction::Sent {
            chain: Chain::Zcash,
            tx_hash: "deadbeef".to_string(),
            amount_zatoshi: 10_000_000,
        };
        let json = serde_json::to_string(&action).unwrap();
        assert!(
            json.contains("\"amount_zatoshi\":10000000"),
            "amount_zatoshi must serialize as integer, got: {json}"
        );
        assert!(
            !json.contains("\"amount\""),
            "old 'amount' field must not be present, got: {json}"
        );
    }

    #[test]
    fn payment_action_request_roundtrip_preserves_zatoshi() {
        // Oracle: roundtrip is valid here because we are testing serde consistency
        // (not cryptographic correctness) — the oracle is the ZEC unit definition
        // applied at construction time.
        // 42 ZEC = 4_200_000_000 zatoshi (42 * 10^8).
        let original = PaymentAction::Request {
            chain: Chain::Zcash,
            amount_zatoshi: 4_200_000_000,
        };
        let json = serde_json::to_string(&original).unwrap();
        let decoded: PaymentAction = serde_json::from_str(&json).unwrap();
        let PaymentAction::Request { amount_zatoshi, .. } = decoded else {
            panic!("wrong variant after roundtrip");
        };
        // Oracle: 42 ZEC * 10^8 = 4_200_000_000 zatoshi
        assert_eq!(amount_zatoshi, 4_200_000_000u64);
    }

    #[test]
    fn payment_action_request_old_string_format_is_rejected() {
        // Wire format breaking change: the old format used amount:String.
        // New clients must reject old-format messages (missing required field
        // amount_zatoshi) rather than silently accepting them with amount=0.
        // Oracle: serde requires all non-optional fields to be present.
        let old_format = r#"{"action":"request","chain":"zcash","amount":"0.1"}"#;
        let result: Result<PaymentAction, _> = serde_json::from_str(old_format);
        assert!(
            result.is_err(),
            "old string-amount wire format must be rejected, got: {result:?}"
        );
    }

    #[test]
    fn file_header_roundtrips() {
        use uuid::Uuid;
        let transfer_id = Uuid::new_v4();
        let msg = ClearMessage::FileHeader {
            transfer_id,
            name: "photo.jpg".to_string(),
            size_bytes: 123456,
            sha256_hex: "a".repeat(64),
            total_chunks: 3,
            mime_type: "image/jpeg".to_string(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"type\":\"file_header\""), "got: {json}");
        assert!(json.contains("\"name\":\"photo.jpg\""), "got: {json}");
        let decoded: ClearMessage = serde_json::from_str(&json).unwrap();
        let ClearMessage::FileHeader {
            name,
            size_bytes,
            total_chunks,
            ..
        } = decoded
        else {
            panic!("wrong variant after roundtrip");
        };
        assert_eq!(name, "photo.jpg");
        assert_eq!(size_bytes, 123456);
        assert_eq!(total_chunks, 3);
    }

    #[test]
    fn file_chunk_data_is_base64_in_json() {
        // Oracle: base64 of [0xFF; 3] is "/////w==" is wrong, let's use [0xDE, 0xAD, 0xBE] → "3q2+"
        // Actually oracle: base64(0xFF, 0xFF, 0xFF) = "////" per RFC 4648 Table 1
        // Use known value: [0x00, 0x00, 0x00] → "AAAA"
        use uuid::Uuid;
        let transfer_id = Uuid::new_v4();
        let data = vec![0x00u8, 0x00, 0x00];
        let msg = ClearMessage::FileChunk {
            transfer_id,
            seq: 0,
            data: data.clone(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        // data field must be a base64 string, not a JSON array
        let v: serde_json::Value = serde_json::from_str(&json).unwrap();
        let data_field = v["data"]
            .as_str()
            .expect("data must be a string (base64), not array");
        // Oracle: base64([0x00, 0x00, 0x00]) = "AAAA" per RFC 4648
        assert_eq!(data_field, "AAAA", "base64 of [0,0,0] must be 'AAAA'");
    }

    #[test]
    fn file_chunk_roundtrips_binary_data() {
        use uuid::Uuid;
        let transfer_id = Uuid::new_v4();
        // 48KB of cycling byte values 0..=255
        let data: Vec<u8> = (0u8..=255).cycle().take(48 * 1024).collect();
        let msg = ClearMessage::FileChunk {
            transfer_id,
            seq: 7,
            data: data.clone(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        let decoded: ClearMessage = serde_json::from_str(&json).unwrap();
        let ClearMessage::FileChunk { seq, data: got, .. } = decoded else {
            panic!("wrong variant");
        };
        assert_eq!(seq, 7);
        assert_eq!(
            got, data,
            "48KB binary data must survive JSON roundtrip via base64"
        );
    }
}

impl std::fmt::Display for Chain {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Chain::Zcash => write!(f, "ZEC"),
            Chain::Monero => write!(f, "XMR"),
            Chain::Mobilecoin => write!(f, "MOB"),
        }
    }
}

/// Pad `plaintext` into a fixed-size bucket to hide payload length.
///
/// Buckets: 256, 512, 1024, 4096, 65536 bytes.
/// Layout: `u32le(len) || plaintext || zero-padding`.
/// Maximum plaintext is 65532 bytes (65536 − 4-byte length prefix).
pub fn pad(plaintext: &[u8]) -> Result<Vec<u8>> {
    const BUCKETS: [usize; 5] = [256, 512, 1024, 4096, 65536];
    let total_needed = 4 + plaintext.len();
    let bucket = BUCKETS
        .iter()
        .copied()
        .find(|&b| b >= total_needed)
        .ok_or_else(|| {
            anyhow::anyhow!(
                "payload too large: {} bytes exceeds 65532-byte maximum",
                plaintext.len()
            )
        })?;
    let mut out = Vec::with_capacity(bucket);
    let len = plaintext.len() as u32;
    out.extend_from_slice(&len.to_le_bytes());
    out.extend_from_slice(plaintext);
    out.resize(bucket, 0u8);
    Ok(out)
}

/// Recover the original plaintext from a padded buffer produced by [`pad`].
pub fn unpad(padded: &[u8]) -> Result<Vec<u8>> {
    if padded.len() < 4 {
        bail!("padded buffer too short: {} bytes", padded.len());
    }
    let original_len = u32::from_le_bytes(padded[..4].try_into().unwrap()) as usize;
    if 4 + original_len > padded.len() {
        bail!(
            "padded buffer corrupt: declared length {} exceeds buffer",
            original_len
        );
    }
    Ok(padded[4..4 + original_len].to_vec())
}

#[cfg(test)]
mod pad_tests {
    use super::*;

    #[test]
    fn pad_empty_lands_in_256_bucket() {
        let out = pad(&[]).unwrap();
        assert_eq!(out.len(), 256);
        let back = unpad(&out).unwrap();
        assert_eq!(back, b"");
    }

    #[test]
    fn pad_roundtrip_small() {
        let data = b"hello world";
        let out = pad(data).unwrap();
        assert_eq!(out.len(), 256); // 4+11=15 < 256
        let back = unpad(&out).unwrap();
        assert_eq!(back, data);
    }

    #[test]
    fn pad_roundtrip_at_bucket_boundary_252() {
        // 4 + 252 = 256 exactly fits 256 bucket
        let data = vec![0xab; 252];
        let out = pad(&data).unwrap();
        assert_eq!(out.len(), 256);
        let back = unpad(&out).unwrap();
        assert_eq!(back, data);
    }

    #[test]
    fn pad_roundtrip_at_253_uses_512_bucket() {
        // 4 + 253 = 257 > 256, so next bucket is 512
        let data = vec![0xcd; 253];
        let out = pad(&data).unwrap();
        assert_eq!(out.len(), 512);
        let back = unpad(&out).unwrap();
        assert_eq!(back, data);
    }

    #[test]
    fn pad_roundtrip_max_4092() {
        let data = vec![0xef; 4092];
        let out = pad(&data).unwrap();
        assert_eq!(out.len(), 4096);
        let back = unpad(&out).unwrap();
        assert_eq!(back, data);
    }

    #[test]
    fn pad_too_large_returns_err() {
        let data = vec![0u8; 65533];
        assert!(pad(&data).is_err());
    }

    #[test]
    fn pad_accepts_65532_bytes() {
        let data = vec![0xabu8; 65532];
        let out = pad(&data).unwrap();
        assert_eq!(out.len(), 65536);
        let back = unpad(&out).unwrap();
        assert_eq!(back, data);
    }

    #[test]
    fn unpad_too_short_returns_err() {
        assert!(unpad(&[0u8; 3]).is_err());
    }

    #[test]
    fn unpad_corrupt_length_returns_err() {
        // declare length 100 but only 10 bytes follow
        let mut buf = vec![0u8; 8];
        buf[0] = 100; // u32le = 100, but buf is only 8 bytes total
        assert!(unpad(&buf).is_err());
    }
}
