// AUTO-GENERATED by flutter_rust_bridge_codegen.
// DO NOT EDIT by hand.
//
// This file is generated by running:
//   flutter_rust_bridge_codegen generate \
//     --rust-input ../ffi/src/api \
//     --dart-output lib/src/rust
//
// In CI (codemagic.yaml) this is regenerated before each build.
// Commit this file when regenerated locally to keep the repo buildable.

// ignore_for_file: unused_import, unused_element

import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initializes the Rust FFI layer. Must be called before any FFI function.
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  static Future<void> init({
    ExternalLibrary? dylib,
    bool appendDotDylib = false,
  }) async {
    await instance.initImpl(
      debugName: 'nie_ffi',
      dylib: dylib,
      appendDotDylib: appendDotDylib,
    );
  }

  static Future<void> dispose() async => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers(RustLibApi api) async {
    await api.initApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.7.0';

  @override
  int get rustContentHash => 0;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'nie_ffi',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {}
class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({required super.handler, required super.wire, required super.generalizedFrbRustBinding, required super.portManager});
}

// ignore: camel_case_types
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) => RustLibWire();
}
