// AUTO-GENERATED by flutter_rust_bridge_codegen.
// DO NOT EDIT by hand.  Regenerate with:
//   flutter_rust_bridge_codegen generate \
//     --rust-input ../ffi/src/api \
//     --dart-output lib/src/rust

// ignore_for_file: unused_import, camel_case_types

import '../frb_generated.dart';

// ---------------------------------------------------------------------------
// NieEvent sealed class hierarchy
// ---------------------------------------------------------------------------

sealed class NieEvent {
  const NieEvent();
}

final class NieEvent_MessageReceived extends NieEvent {
  final String from;
  final String text;
  const NieEvent_MessageReceived({required this.from, required this.text});
}

final class NieEvent_WhisperReceived extends NieEvent {
  final String from;
  final String text;
  const NieEvent_WhisperReceived({required this.from, required this.text});
}

final class NieEvent_UserJoined extends NieEvent {
  final String pubId;
  final String? nickname;
  final int sequence;
  const NieEvent_UserJoined({required this.pubId, this.nickname, required this.sequence});
}

final class NieEvent_UserLeft extends NieEvent {
  final String pubId;
  const NieEvent_UserLeft({required this.pubId});
}

final class NieEvent_DirectoryUpdated extends NieEvent {
  final List<NieUserEntry> online;
  const NieEvent_DirectoryUpdated({required this.online});
}

final class NieEvent_UserNickname extends NieEvent {
  final String pubId;
  final String nickname;
  const NieEvent_UserNickname({required this.pubId, required this.nickname});
}

final class NieEvent_Reconnecting extends NieEvent {
  final int delaySecs;
  const NieEvent_Reconnecting({required this.delaySecs});
}

final class NieEvent_Reconnected extends NieEvent {
  const NieEvent_Reconnected();
}

// ---------------------------------------------------------------------------
// NieUserEntry
// ---------------------------------------------------------------------------

class NieUserEntry {
  final String pubId;
  final String? nickname;
  final int sequence;

  const NieUserEntry({
    required this.pubId,
    this.nickname,
    required this.sequence,
  });
}

// ---------------------------------------------------------------------------
// NieClient opaque handle
// ---------------------------------------------------------------------------

class NieClient {
  // Opaque handle — holds a pointer to the Rust NieClient struct.
  // Implementation generated by FRB codegen; stub for IDE support.
  const NieClient._();
}

// ---------------------------------------------------------------------------
// FFI functions (stubs — real implementations generated by FRB codegen)
// ---------------------------------------------------------------------------

Future<NieClient> clientConnect({
  required String relayUrl,
  required String secretB64,
  required bool acceptInvalidCerts,
}) =>
    throw UnimplementedError('call flutter_rust_bridge_codegen generate');

Future<NieEvent?> clientNextEvent({required NieClient client}) =>
    throw UnimplementedError('call flutter_rust_bridge_codegen generate');

String clientPubId({required NieClient client}) =>
    throw UnimplementedError('call flutter_rust_bridge_codegen generate');

Future<void> clientSendMessage({required NieClient client, required String text}) =>
    throw UnimplementedError('call flutter_rust_bridge_codegen generate');

Future<void> clientSendWhisper({
  required NieClient client,
  required String to,
  required String text,
}) =>
    throw UnimplementedError('call flutter_rust_bridge_codegen generate');

Future<void> clientSetNickname({required NieClient client, required String nickname}) =>
    throw UnimplementedError('call flutter_rust_bridge_codegen generate');

void clientDisconnect({required NieClient client}) =>
    throw UnimplementedError('call flutter_rust_bridge_codegen generate');
