// AUTO-GENERATED by flutter_rust_bridge_codegen.
// DO NOT EDIT by hand.  Regenerate with:
//   flutter_rust_bridge_codegen generate \
//     --rust-input ../ffi/src/api \
//     --dart-output lib/src/rust

// ignore_for_file: unused_import, camel_case_types

import '../frb_generated.dart';

/// Generate a fresh Ed25519 + X25519 identity.
///
/// Returns a base64-encoded 64-byte secret blob.
/// The caller must store this securely and must never log it.
String generateIdentity() => throw UnimplementedError('call flutter_rust_bridge_codegen generate');

/// Derive the public ID (64 lowercase hex chars) from a base64-encoded 64-byte secret.
String pubIdFromSecret({required String secretB64}) =>
    throw UnimplementedError('call flutter_rust_bridge_codegen generate');

/// Save the identity secret to a file at [path].
///
/// On Android, [path] should be inside `context.filesDir`.
Future<void> saveIdentityToFile({required String path, required String secretB64}) =>
    throw UnimplementedError('call flutter_rust_bridge_codegen generate');

/// Load the identity secret from a file at [path].
///
/// Returns `null` if the file does not exist (first-run case).
Future<String?> loadIdentityFromFile({required String path}) =>
    throw UnimplementedError('call flutter_rust_bridge_codegen generate');
